### PR TITLE
add python3.7 to travis

### PR DESCRIPTION
**Pull request by bfredl**

### CODE REVIEW

**Comment by bfredl** [comment]
This was no fun:
```
Setting APT mirror in /etc/apt/sources.list: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

**Comment by justinmk** [comment]
Looks like open issue: https://github.com/travis-ci/travis-ci/issues/9815

**Comment by mhinz** [comment]
[Travis CI is phasing out its support for containers](https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures), so `sudo: false` is not that useful anymore. I think just adding `dist: xenial` will make the `python: 3.7` work.

**Comment by blueyed** [comment]
Yes, xenial should work without sudo, but dist should be trusty then for py34.

**Comment by blueyed** [comment]
Looks like they fixed py34, I am going to create a new PR for this.

**Pull request merged**
