### PR TITLE
WIP: appveyor

### PR DESCRIPTION
**Pull request by bfredl**
Inspired by the [neovim-ruby script](https://github.com/alexgenco/neovim-ruby/blob/master/appveyor.yml)

### CODE REVIEW

**Comment by bfredl** [comment]
Almost there:
```
python -m nose
72
.............................E.......................
73
======================================================================
74
ERROR: test_vim.test_command
75
----------------------------------------------------------------------
76
Traceback (most recent call last):
77
  File "C:\Python35\lib\site-packages\nose\case.py", line 198, in runTest
78
    self.test(*self.arg)
79
  File "C:\projects\python-client\test\test_vim.py", line 26, in test_command
80
    os.unlink(fname)
81
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpaq48lhk5'
82
```

**Comment by justinmk** [comment]
https://github.com/neovim/python-client/commit/a2e1169952fb8c0c8a618a69f04a686ad37e3cc4 was supposed to fix that. Maybe try a local `@with_setup` function.

**Comment by blueyed** [comment]
Is the problem maybe Neovim having the file open? (https://github.com/neovim/python-client/commit/a2e1169952fb8c0c8a618a69f04a686ad37e3cc4#diff-a5d6c1e0ffb8d50d5794662b1a7cabeaR18)

/cc @brcolow

**Comment by justinmk** [comment]
sure, let's try `:bwipeout` then.

**Comment by blueyed** [comment]
Would be good to disable the Appveyor check in the Github settings to not get an X because of the missing config in other PRs.
Might also be a AppVeyor setting though IIRC.

**Comment by blueyed** [comment]
(or get this PR in, of course.. :))

**Comment by bfredl** [comment]
Sorry been busy with other stuff. Just made the second attempt of asyncio on windows, let's see if appveyor likes it...

**Comment by justinmk** [comment]
Github actions runs Windows, though tests are failing on Windows currently.

**Pull request closed without merging**
