### PR TITLE
ci: fix coverage reporting

### PR DESCRIPTION
**Pull request by blueyed**
Add "cov" tox factor, which should get used by tox-travis then.

### CODE REVIEW

**Comment by blueyed** [comment]
Might not need codecov - initially fixed it because Scrutinizer was failing/erroring due to it.

**Comment by blueyed** [comment]
It was uploaded for Scrutinizer (https://travis-ci.org/neovim/pynvim/jobs/573872712#L526), but it is still pending: https://scrutinizer-ci.com/g/neovim/pynvim/inspections/f60fbc9e-04de-4810-8196-7520f3b83117

Apparently waiting for the upload for master, which is not going to happen.

Therefore I think this is ready, and then should be fixed for future PRs.

**Comment by blueyed** [comment]
@bfredl @justinmk 
OK to merge?

**Comment by bfredl** [comment]
looks ok to me.

**Comment by justinmk** [comment]
I don't think we want those codecov comments on PRs. Does this enable those somehow?

**Comment by blueyed** [comment]
@justinmk 
They are disabled in the config: https://github.com/neovim/pynvim/pull/408/files#diff-1f7b4b85ed8525c5239f741431a72872R6
Probably not working properly for the initial addition of it etc.
And while it might still happen due to bugs with them (as seen with neovim/neovim sometimes), they should not appear normally.

**Pull request merged**
